export const CURRENT_HANG_ID = 'CURRENT_HANG_ID';
export const CURRENT_CART_BILL_ID = 'CURRENT_CART_BILL_ID';
export const CURRENT_CART_ORDER_ID = 'CURRENT_CART_ORDER_ID';
export const CURRENT_CART_THU_ID = 'CURRENT_CART_THU_ID';




export const GET_LIST_HANG = 'GET_LIST_HANG';


export const GET_LIST_SUPPLIER = 'GET_LIST_SUPPLIER';

export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';



export const UPDATE_LIST_ALL_COLOR = 'UPDATE_LIST_ALL_COLOR';

export const UPDATE_LIST_ALL_SIZE = 'UPDATE_LIST_ALL_SIZE'